export const SAVE_DELIVERY_ADDRESS = "SAVE_DELIVERY_ADDRESS";
export const EDIT_DELIVERY_ADDRESS = "EDIT_DELIVERY_ADDRESS";

export const PAID_ORDER = "PAID_ORDER";
export const NOT_PAID_ORDER = "NOT_PAID_ORDER";

export const CREATE_ORDER_REQUEST = "CANCEL_DELIVERY_ADDRESS";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";